import { Maven_Pro, Sora } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import Wrapper from "@/components/layout/Wrapper";

const inter = Sora({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
});

export const metadata = {
  title: "E-Commerce App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Wrapper>
          <Header />
          {/* <main className="px-8"> */}
          {children}
          {/* </main> */}
          <Footer />
        </Wrapper>
      </body>
    </html>
  );
}
